src/backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('services/', include('services.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/backend/home/urls.py
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from . import views

# URLConf
app_name = 'home'
favicon_view = RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)
urlpatterns = [
    path('', views.get_home_page, name='home_page'),
    path('top/', views.get_home_page, name='home_page'),
    path('details/<movie_id>', views.movie_details, name='movie-details'),
    path('like_movie/<int:pk>', views.like_movie, name="like-movie"),
    path('like/', views.like, name='like'),
    path('dislike/', views.dislike, name='dislike'),
    path('search', views.search_movies, name='movie-search'),
    path('evaluate/', views.get_eval, name='eval'),
    path('erase/', views.erase_comment, name='erase'),
    path('add_movie/<int:pk>', views.add_movie_to_watchlist, name="add-to-watchlist"),
    path('check_movie_seen/<int:pk>', views.check_movie_seen, name="seen_movie"),
    re_path(r'^favicon\.ico$', favicon_view),
]

src/backend/members/urls.py
from django.urls import path
from . import views

# URLConf
app_name = 'members'
urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('<int:user_id>/watchlist', views.get_watchlist_page, name='watchlist'),
    path('home/', views.home, name='home'),
    path('logout', views.logout_user, name='logout'),
    path('<int:user_id>/profile', views.get_profile_page, name='profile'),
    path('LoggedProfile/', views.login_user_profile, name='logged_profile_user'),
    path('set_regular/', views.set_regular, name='regular'),
    path('set_premium/', views.set_premium, name='premium'),
    path('set_pro/', views.set_pro, name='pro')
]

src/backend/members/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    user_since = models.DateTimeField(auto_now_add=True)
    is_regular_user = models.BooleanField('Is Regular', default=True)
    is_premium_user = models.BooleanField('Is Premium', default=False)
    is_pro_user = models.BooleanField('Is Pro', default=False)
    profile_pic = models.ImageField(null=True, blank=True, upload_to="image/profile/")
    description = models.TextField(default="This is the description field.")

src/backend/members/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from home.models import Comments
from django.forms import ModelForm


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    fields = ('username', 'password')


class Profile(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'profile_pic', 'description')
        help_texts = {
            'username': None,
        }


class SignUpForm(UserCreationForm):
    class Meta:
        model = User

        first_name = forms.CharField(
            widget=forms.TextInput(
                attrs={
                    "class": "form-control"
                }
            )
        )

        last_name = forms.CharField(
            widget=forms.TextInput(
                attrs={
                    "class": "form-control"
                }
            )
        )

        username = forms.CharField(
            widget=forms.TextInput(
                attrs={
                    "class": "form-control"
                }
            )
        )
        password1 = forms.CharField(
            widget=forms.PasswordInput(
                attrs={
                    "class": "form-control"
                }
            )
        )

        password2 = forms.CharField(
            widget=forms.PasswordInput(
                attrs={
                    "class": "form-control"
                }
            )
        )

        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

        widgets = {
            'first_name': forms.TextInput(attrs={"class": "form-control"}),
            'last_name': forms.TextInput(attrs={"class": "form-control"}),
            'username': forms.TextInput(attrs={"class": "form-control"}),
            'password1': forms.PasswordInput(attrs={"class": "form-control"}),
            'password2': forms.PasswordInput(attrs={"class": "form-control"}),
            'email': forms.EmailInput(attrs={"class": "form-control"}),
        }

src/backend/members/views.py
from django.contrib.auth.decorators import permission_required, user_passes_test
from django.shortcuts import render, redirect
from .forms import SignUpForm, LoginForm, Profile
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth import logout
from home.models import Comments, GenderMovies
from django.shortcuts import get_object_or_404
from .models import User
from home.models import Movie


# Create your views here.
def register(request):
    msg = None

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            msg = 'user created'
            return redirect('members:login_user')
        else:
            msg = 'form is not valid'
    else:
        form = SignUpForm()
    return render(request, 'register.html', {'form': form, 'msg': msg})


def login_user(request):
    form = LoginForm(request.POST or None)
    msg = None
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home:home_page')
            else:
                messages.success(request, "Invalid Credentials")
                return redirect('members:login_user')
    else:
        msg = 'error validation form'
        return render(request, 'authenticate/login.html', {'form': form})


def home(request):
    return render(request, 'index.html')


def login_user_profile(request):
    user = request.user
    comments = Comments.objects.filter(critic_id=user.id).order_by('-entry')
    form = Profile(instance=user)
    if request.method == 'POST':
        form = Profile(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
    return render(request, 'user_profile.html', {'form': form, 'comments': comments, 'myuser': user})


def get_profile_page(request, user_id):
    comments_context = Comments.objects.filter(critic_id=user_id).order_by('-entry')
    user_context = User.objects.get(pk=user_id)
    return render(request, 'profile.html', {'critic': user_context, 'comments': comments_context})


def user_is_not_regular_check(user):
    if user.is_premium_user is False and user.is_pro_user is False:
        return False
    else:
        return True


def get_watchlist_page(request, user_id):
    movies = Movie.objects.filter(watch_list=user_id)
    gender_set = set()
    for movie in movies:
        genders = movie.gender.all()
        for g in genders:
            gender_set.add(g.gender)
    if request.method == 'POST':
        if request.POST['order'] == 'alphabet':
            movies = Movie.objects.filter(watch_list=user_id).order_by("name")
            return render(request, 'watchlist.html', {'movies': movies, 'genres': gender_set})
        if request.POST['order'] == 'year':
            movies = Movie.objects.filter(watch_list=user_id).order_by("raw__year")
            return render(request, 'watchlist.html', {'movies': movies, 'genres': gender_set})
        if request.POST['order']:
            res: str = request.POST.get('order')
            if res.isdigit():
                movies = Movie.objects.filter(watch_list=user_id)
                movie_to_erase = get_object_or_404(Movie, id=res)
                movie_to_erase.watch_list.remove(request.user)
                return render(request, 'watchlist.html', {'movies': movies, 'genres': gender_set})
            else:
                gender = GenderMovies.objects.get(gender=res)
                movies = Movie.objects.filter(watch_list=user_id, gender=gender.id)
                return render(request, 'watchlist.html', {'movies': movies, 'genres': gender_set})
    return render(request, 'watchlist.html', {'movies': movies, 'genres': gender_set})


def logout_user(request):
    logout(request)
    form = LoginForm(request.POST or None)
    msg = None
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home:home_page')
            else:
                messages.success(request, "Invalid Credentials")
                return redirect('members:login_user')
    else:
        msg = 'error validation form'
        return render(request, 'authenticate/login.html', {'form': form})


def set_regular(request):
    user = User.objects.get(pk=request.user.id)
    user.is_premium_user = False
    user.is_pro_user = False
    user.save()
    comments = Comments.objects.filter(critic_id=user.id).order_by('-entry')
    form = Profile(instance=user)
    if request.method == 'POST':
        form = Profile(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
    return render(request, 'user_profile.html', {'form': form, 'comments': comments, 'myuser': user})


def set_premium(request):
    user = User.objects.get(pk=request.user.id)
    user.is_premium_user = True
    user.is_pro_user = False
    user.save()
    comments = Comments.objects.filter(critic_id=user.id).order_by('-entry')
    form = Profile(instance=user)
    if request.method == 'POST':
        form = Profile(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
    return render(request, 'user_profile.html', {'form': form, 'comments': comments, 'myuser': user})


def set_pro(request):
    user: User = User.objects.get(pk=request.user.id)
    user.is_premium_user = False
    user.is_pro_user = True
    user.save()
    comments = Comments.objects.filter(critic_id=user.id).order_by('-entry')
    form = Profile(instance=user)
    if request.method == 'POST':
        form = Profile(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
    return render(request, 'user_profile.html', {'form': form, 'comments': comments, 'myuser': user})

src/backend/members/templates/register.html
{% extends 'base.html' %}
<html>
  <body class="">
    {% block content %}
    <section id="main">
      <form action="" method=POST>

         {% csrf_token %}
         {{form.as_p}}

         <input type="submit" value="Submit" class="Registar">

        </ul>
      </form>
    </section>
    {% endblock content %}
  </body>
</html>

src/backend/members/templates/user_profile.html
{% extends 'base.html' %}
{% load static %}
<html>
  {% block extrastyle %}
  <link rel="stylesheet" href="{% static '../static/assets/css/main2.css' %}" />
  {% endblock extrastyle %}
  <body class="is-preload">
    {% block content %}
    <div id="main">
      <article class="post featured" style="padding-bottom: 2rem !important;">
        <header class="major">
          <span class="date">Updated IMDB List</span>
          <h2>
            <a
              >Welcome to<br />
              Your Profile Page
            </a
            >
          </h2>
          <p>
            Here you can find your personal info that you shared with us! <br />
            For any information please contact the website administrator.
          </p>
        </header>
        <ul class="actions special">
          <li>
            <a href="{% url 'members:regular' %}" class="button large"
              >Get Regular</a>
          </li>
          <li>
            <a href="{% url 'members:premium' %}" class="button large"
              >Get Premium</a>
          </li>
          <li>
            <a href="{% url 'members:pro' %}" class="button large"
              >Get Pro</a>
          </li>
        </ul>
      </article>
      <hr style="width: 90% !important; margin-left: 5%;" />
      <!-- Posts -->
      <center style="padding-bottom: 2px !important;">
        <section class="posts">
          <article>
            <header>
              <span class="date">Member since: {{ user.user_since }}</span>
                <h2 style="font-size: 20px !important">{{ user.first_name }} - {% if myuser.is_pro_user %} Pro User {% endif %}{% if myuser.is_premium_user %} Premium User {% endif %}
                  {% if myuser.is_regular_user == True and myuser.is_premium_user == False and myuser.is_pro_user == False %} Regular User {% endif %}
                </h2>
            </header>
            <br>
            {% if request.user.profile_pic %}
                <img
                  src= "{{ request.user.profile_pic.url }}"
                  style="max-width: 25%; max-height: 25%; border-radius: 50%"
                />
            {% else %}
            <img src="{% static 'default-user-image.png' %}"
                 style="max-width: 25%; max-height: 25%; border-radius: 50%"/>
            {% endif %}
            <br><br>
           <p2>{{ request.user.description }}</p2><br /><br />
            <p2><b>Email:</b> {{ request.user.email }}</p2>
          </article>
        </section>
      </center>
      <br><br>
      <div style="display:inline; padding-right: 0 !important; cursor: pointer;" 
      onclick="revealinfo('info-slide')" 
      id="info-slide"
      onmouseover="increaseover('info-slide')"
      onmouseout="decreaseout('info-slide')">
      <i class="fas fa-arrow-right" id="arrow-slide"></i>
      <h2 style="display:inline; font-size: larger; padding: 0 0 0 0.5rem !important;" id="info-slide-text">Edit Personal Info:</h2>
      </div>
      <div style="display: none; padding-top: 30px !important; padding-bottom: 2px !important;" id="form-edit-personalinfo">
        <form method=POST action="" enctype="multipart/form-data">
          {% csrf_token %}
          {{form.as_p}}
          <button class="btn btn-secondary">Post</button>
        </form>
      </div>
      <br>
      <br>
        <h2 style="display:inline; font-size: larger; border:none;">My Comments</h2>
        <hr style="width: 90% !important; margin-left: 5%;" />
        {% for comment in comments %}
        <section class="comment-list">
          <article class="row">
            <div class="col-md-2 col-sm-2 hidden-xs">
              <div class="col-md-10 col-sm-10">
                <div class="panel-body" style="display: inline">
                  <header class="text-left">
                    <div class="comment-user">
                      <i class="fa fa-user"></i><a href="{% url 'members:profile' comment.critic_id %}"> {{ comment.critic_username }}</a>
                      &nbsp;
                      <i class="fa fa-film"></i><a href="{% url 'home:movie-details' comment.movie_id %}"> {{ comment.movie_name }}</a>
                    </div>
                    <time class="comment-date" datetime="16-12-2014 01:05">
                      <i class="fa fa-clock-o"></i>{{ comment.entry }}</time>
                  </header>
                </div>
                <div class="comment-post">
                  <p>
                    <strong>{{ comment.title }}</strong><br />
                    {{ comment.comment }}
                  </p>
                </div>
                <div style="display: flex; height: 16px !important;" class="text-right">
                  <i id="{{ comment.id }}-aifeedback"
                    onmouseover="doThis('{{ comment.id }}', '{{ comment.AI_FeedBack }}')"
                    style="cursor: pointer;"
                    onclick="doThat('{{ comment.id }}')" class="fa fa-search"></i>
                  <h2 style="display:none; margin-bottom: 0 !important; font-size: large !important;"
                    id="{{ comment.id }}-aiscore">&nbsp;<b>AI Score:</b></h2>&nbsp;<h2
                    style="display:none; margin-bottom: 0 !important; font-size: large !important;"
                    id="{{ comment.id }}-nota">
                  </h2>
                  &nbsp;
                  <div style="display: flex; height: 16px !important;" class="text-right">
                    <i id="{{ comment.id }}-likebutton"
                      style="cursor: pointer;"
                      onmouseover="doThisThumbsup('{{ comment.id }}')"
                      class="fas fa-thumbs-up"></i>
                  </div>
                  &nbsp;

                  <h2 id="{{ comment.id }}-likesprofile"
                    style="color: black; display: none; margin-bottom: 0 !important; font-size: large !important;">
                    {{ comment.likes }} likes &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                  </h2>

                  {% if comment.critic_feedback == False and myuser.is_pro_user == True %}
                  &nbsp; &nbsp;
                  <div style="display: flex; height: 16px !important;margin-left: auto !important;" class="text-right">
                 <h2 id="{{ comment.id }}-question" style="display: inline !important; font-size: large !important; margin-left: auto !important;">Do you agree with the AI?</h2>
                 &nbsp;
                   <button style="all: unset !important; cursor: pointer;" type="submit" class="check-button"
                   data-rowid="{{ comment.id }}" value="{{ comment.id }}-1" id="check-button-{{ comment.id }}">
                   <span id="{{ comment.id }}-agreewithai"
                     style="vertical-align: 12px; padding-top: 3px; padding-left: 5px; cursor: pointer;"
                     onmouseover="doThisAgreeWithAI('{{ comment.id }}')"
                     onmouseout="doThisAgreeWithAI_out('{{ comment.id }}')"
                     class="fas fa-check"></span>
                   </button>
                   <button style="all: unset !important; cursor: pointer;" type="submit" class="times-button"
                   data-rowid="{{ comment.id }}" value="{{ comment.id }}-0" id="times-button-{{ comment.id }}">
                   <span id="{{ comment.id }}-disagreewithai"
                     style="vertical-align: 12px; padding-top: 3px; padding-left: 8px; cursor: pointer;"
                     onmouseover="doThisDisagreeWithAI('{{ comment.id }}')"
                     onmouseout="doThisDisagreeWithAI_out('{{ comment.id }}')"
                     class="fa fa-times"></span>
                     </button>
               </div>
                 {% endif %}
                </div>
              </div>
            </div>
          </article>
          <hr />
          {% endfor %}
          <br><br>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script>
    $(document).on('click', '.check-button', function (e) {
      e.preventDefault();
      var rowid = $(this).data('rowid')
      var check_button = "#check-button-" + rowid
      $.ajax({
        type: 'POST',
        url: '{% url "home:eval" %}',
        data: {
          postid: $(check_button).val(),
          csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken').val(),
          action: 'post'
        },
        success: function (json) {
          var nota_id = json['p_id'] + "-nota"
          var question_id = json['p_id'] + "-question"
          var checkbutton_id = json['p_id'] + "-agreewithai"
          var timebutton_id = json['p_id'] + "-disagreewithai"
          document.getElementById(nota_id).value = ""
          document.getElementById(question_id).value = ""
          document.getElementById(nota_id).innerHTML = json['result']
          if(json['result'] == "negative"){
            document.getElementById(nota_id).style.color = "red";
          } else {
            document.getElementById(nota_id).style.color = "green";
          }
          document.getElementById(question_id).innerHTML = "Avaliação submetida com sucesso!"
          document.getElementById(nota_id).style.display = "inline"
          document.getElementById(checkbutton_id).remove()
          document.getElementById(timebutton_id).remove()
          console.log(json)
        },
        error: function (xhr, errmsg, err) {

        }
      });
    })

    $(document).on('click', '.times-button', function (e) {
      e.preventDefault();
      var rowid = $(this).data('rowid')
      var times_button = "#times-button-" + rowid
      $.ajax({
        type: 'POST',
        url: '{% url "home:eval" %}',
        data: {
          postid: $(times_button).val(),
          csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken').val(),
          action: 'post'
        },
        success: function (json) {
          var nota_id = json['p_id'] + "-nota"
          var question_id = json['p_id'] + "-question"
          var checkbutton_id = json['p_id'] + "-agreewithai"
          var timebutton_id = json['p_id'] + "-disagreewithai"
          document.getElementById(nota_id).value = ""
          document.getElementById(question_id).value = ""
          document.getElementById(nota_id).innerHTML = json['result']
          if(json['result'] == "negative"){
            document.getElementById(nota_id).style.color = "red";
          } else {
            document.getElementById(nota_id).style.color = "green";
          }
          document.getElementById(question_id).innerHTML = "Avaliação submetida com sucesso!"
          document.getElementById(nota_id).style.display = "inline"
          document.getElementById(checkbutton_id).remove()
          document.getElementById(timebutton_id).remove()
          console.log(json)
        },
        error: function (xhr, errmsg, err) {
        }
      });
    })
  </script>
    {% endblock content %}
  </body>
</html>

src/backend/members/templates/watchlist.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html>
  <body class="is-preload">
    {% block content %}

    <div id="main">
      
      <ul class="actions special">
        <li>
          <form action="{% url 'members:watchlist' request.user.id %}"
                method="POST" id="submityear">
                {% csrf_token %}
          <input type="hidden" name="order" value="year">
          <a class="button large" {% if user.is_pro_user %} onclick="document.getElementById('submityear').submit();" {% else %} onclick="getpro()" {% endif %}
            >Order by Year</a>
          </input>
        </form>
        </li>
        <li>
          <form action="{% url 'members:watchlist' request.user.id %}"
                method="POST" id="submitalphabetically">
                {% csrf_token %}
          <input type="hidden" name="order" value="alphabet">
          <a class="button large" {% if user.is_pro_user %} onclick="document.getElementById('submitalphabetically').submit();" {% else %} onclick="getpro()"{% endif %}
          >Order Alphabetically</a>
        </input>
      </form>
        </li>
        <li>
          <a class="button large" id="drop" {% if user.is_pro_user %} onclick="revealdrop('drop')" {% else %} onclick="getpro()" {% endif %}>Filter Genre</a>
          <p style="z-index: 1 !important; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2) !important; margin-bottom: auto !important">
            {% for genre in genres %}
            <form action="{% url 'members:watchlist' request.user.id %}"
                method="POST" id="submitstuff{{ forloop.counter }}" style="margin-bottom: 0 !important;">
                {% csrf_token %}
            <input type="hidden" name="order" value="{{ genre }}">
            <a class="button large" 
            style="-webkit-box-shadow: 0 0 3.5px #000 !important; height: 1.5rem !important; line-height: 1.5rem !important; display: none !important"
            id="droplist{{ forloop.counter }}" onclick="document.getElementById('submitstuff{{ forloop.counter }}').submit();"
            >{{ genre }}</a>
            </input>
          </form>
            {% endfor %}
          </p>
        </li>
      </ul>
      
      <hr style="width: 90% !important; margin-left: 5%; border-bottom: 0;" />
      
      <section class="posts" style="border-top: 0;">
        {% for movie in movies %}
        <article>
          <header>
            <span class="date">{{ movie.raw | get_movie_year }}</span>
            <h2>
              <a href="{% url 'home:movie-details' movie.id %}"
                >{{ movie.raw | get_movie_name }}</a
              >
            </h2>
          </header>
          <a href="{% url 'home:movie-details' movie.id %}" class="image fit"
            ><img src="{{ movie.raw | get_movie_cover }}" alt=""
          /></a>
          <!-- <p>{{ movie.raw | get_movie_description }}</p> -->
          <ul class="actions special">
            <li>
              <form action="{% url 'members:watchlist' request.user.id %}"
                method="POST" id="submiterase{{ forloop.counter }}">
                {% csrf_token %}
                <input type="hidden" name="order" value="{{ movie.id }}">
              <a class="button" onclick="document.getElementById('submiterase{{ forloop.counter }}').submit();">Remove from Watchlist</a>
            </input>
          </form>
            </li>
          </ul>
        </article>
        {% endfor %}
      </section>
    </div>
    {% endblock content %}
  </body>
</html>