src/backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('services/', include('services.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/backend/home/urls.py
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from . import views

# URLConf
app_name = 'home'
favicon_view = RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)
urlpatterns = [
    path('', views.get_home_page, name='home_page'),
    path('top/', views.get_home_page, name='home_page'),
    path('details/<movie_id>', views.movie_details, name='movie-details'),
    path('like_movie/<int:pk>', views.like_movie, name="like-movie"),
    path('like/', views.like, name='like'),
    path('dislike/', views.dislike, name='dislike'),
    path('search', views.search_movies, name='movie-search'),
    path('evaluate/', views.get_eval, name='eval'),
    path('erase/', views.erase_comment, name='erase'),
    path('add_movie/<int:pk>', views.add_movie_to_watchlist, name="add-to-watchlist"),
    path('check_movie_seen/<int:pk>', views.check_movie_seen, name="seen_movie"),
    re_path(r'^favicon\.ico$', favicon_view),
]

src/backend/members/urls.py
from django.urls import path
from . import views

# URLConf
app_name = 'members'
urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('<int:user_id>/watchlist', views.get_watchlist_page, name='watchlist'),
    path('home/', views.home, name='home'),
    path('logout', views.logout_user, name='logout'),
    path('<int:user_id>/profile', views.get_profile_page, name='profile'),
    path('LoggedProfile/', views.login_user_profile, name='logged_profile_user'),
    path('set_regular/', views.set_regular, name='regular'),
    path('set_premium/', views.set_premium, name='premium'),
    path('set_pro/', views.set_pro, name='pro')
]

src/backend/home/models.py
from email.mime import image

from django.conf import settings
from django.db import models
from members.models import User


# Create your models here.

class GenderMovies(models.Model):
    gender = models.CharField('Movie Gender', max_length=50, blank=True, null=True)


class Movie(models.Model):
    raw = models.JSONField()
    name = models.CharField('Movie Name', max_length=120, blank=True, null=True)
    entry = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='user_likes')
    watch_list = models.ManyToManyField(User, related_name='watch_list_of')
    gender = models.ManyToManyField(GenderMovies, related_name='genders')
    seen = models.ManyToManyField(User, related_name='seen_movie')
    is_top_250 = models.BooleanField(default=False)

    def total_likes(self) -> int:
        return self.likes.choices.count()

    def __str__(self) -> str:
        return self.name.__str__()


class Comments(models.Model):
    title = models.CharField('Title', max_length=500, blank=True, null=True)
    comment = models.TextField('Comment', blank=True, null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    movie_name = models.CharField('Movie_Name', max_length=500, blank=True, null=True)
    critic = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    critic_username = models.CharField('Critic_Name', max_length=500, blank=True, null=True)
    entry = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    AI_FeedBack = models.IntegerField("AiFeedBack", null=True)
    AI_Probability_PositiveFeedBack = models.FloatField("PositiveProbabilityAi", null=True)
    AI_Probability_NegativeFeedBack = models.FloatField("NegativeProbabilityAI", null=True)
    critic_feedback = models.BooleanField("critic_feedback_about_ai_opinion", default=False)


class CommentsLikes(models.Model):
    comment = models.ForeignKey(Comments, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    like = models.BooleanField(default=False)

src/backend/home/views.py
from typing import Dict

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from services import views
import json
from .models import Movie, Comments, CommentsLikes, GenderMovies
from services.scrapper import Scrapper
from services.AIService import AIService
from members.forms import SignUpForm
from services.DictionaryManager import DictionaryManager
from services.ProcessingService import ProcessingService


def like_movie(request, pk):
    id = request.POST.get('movie_id')
    movie = get_object_or_404(Movie, id=id)
    movie_with_like = Movie.objects.filter(likes=request.user.id, id=id)
    if not movie_with_like:
        movie.likes.add(request.user)
        return HttpResponseRedirect(reverse("home:movie-details", args=[int(pk)]))
    else:
        movie.likes.remove(request.user)
        return HttpResponseRedirect(reverse("home:movie-details", args=[int(pk)]))


@login_required(login_url='/members/login_user/')
def movie_details(request, movie_id):
    if request.method == 'POST':
        if 'filter_button_negative' in request.POST:
            movie_id = movie_id
            movie = Movie.objects.get(pk=movie_id)
            comments = Comments.objects.filter(movie=movie, AI_FeedBack=0).order_by('-entry')

            comments_likes_list = list()
            user_id: int = request.user.id
            comments_likes = CommentsLikes.objects.filter(user_id=user_id)
            for com in comments_likes:
                comments_likes_list.extend([int(com.comment_id), com.like])

            return render(request,
                          'details.html',
                          {'movie': movie,
                           'comments': comments,
                           'commentslikes': comments_likes_list,
                           'positive_percentage': 0, })

        if 'filter_button_positive' in request.POST:
            movie_id = movie_id
            movie = Movie.objects.get(pk=movie_id)
            comments = Comments.objects.filter(movie=movie, AI_FeedBack=1).order_by('-entry')

            comments_likes_list = list()
            user_id: int = request.user.id
            comments_likes = CommentsLikes.objects.filter(user_id=user_id)
            for com in comments_likes:
                comments_likes_list.extend([int(com.comment_id), com.like])

            return render(request,
                          'details.html',
                          {'movie': movie,
                           'comments': comments,
                           'commentslikes': comments_likes_list,
                           'positive_percentage': 100, })

        if 'filter_button_user' in request.POST:
            movie_id = movie_id
            movie = Movie.objects.get(pk=movie_id)
            critic_id: int = request.POST.get('filter_button_user')
            comments = Comments.objects.filter(movie=movie, critic_id=critic_id).order_by('-entry')
            positive_percentage = ProcessingService.positive_percentage(comments)

            comments_likes_list = list()
            user_id: int = request.user.id
            comments_likes = CommentsLikes.objects.filter(user_id=user_id)
            for com in comments_likes:
                comments_likes_list.extend([int(com.comment_id), com.like])

            return render(request,
                          'details.html',
                          {'movie': movie,
                           'comments': comments,
                           'commentslikes': comments_likes_list,
                           'positive_percentage': positive_percentage, })

        ai_service: AIService = AIService()
        comment_value = request.POST.get('comentario')
        ai_feedback, neg, pos = ai_service.classify(comment_value)
        movie = Movie.objects.get(pk=movie_id)
        Comments(title=request.POST.get('titulo'),
                 comment=comment_value,
                 movie=movie,
                 movie_name=movie.name,
                 critic=request.user,
                 critic_username=request.user.username,
                 AI_FeedBack=ai_feedback,
                 AI_Probability_PositiveFeedBack=pos,
                 AI_Probability_NegativeFeedBack=neg).save()

    ai_service: AIService = AIService()
    movie = Movie.objects.get(pk=movie_id)
    movie_comments_path = f"https://www.imdb.com{movie.raw['imdb_url']}reviews/?ref_=tt_ql_urv"

    check = Comments.objects.filter(movie=movie.id)
    if not check:
        # Podemos vir a ter um problema aqui caso sejamos nós a adicionar um filme ( solução pode passar por um boolean)
        comments_dictionary: Dict = Scrapper.get_movie_comments(movie_comments_path)
        for keys, value in comments_dictionary.items():
            ai_feedback, neg, pos = ai_service.classify(value)
            Comments(title=keys,
                     comment=value,
                     movie=movie,
                     movie_name=movie.name,
                     critic_username='ImdbUser',
                     AI_FeedBack=ai_feedback,
                     AI_Probability_PositiveFeedBack=pos,
                     AI_Probability_NegativeFeedBack=neg).save()

    comments = Comments.objects.filter(movie=movie).order_by('-entry')
    positive_percentage = ProcessingService.positive_percentage(comments)

    comments_likes_list = list()
    user_id: int = request.user.id
    comments_likes = CommentsLikes.objects.filter(user_id=user_id)
    for com in comments_likes:
        comments_likes_list.extend([int(com.comment_id), com.like])

    return render(request, 'details.html', {'movie': movie,
                                            'comments': comments,
                                            'commentslikes': comments_likes_list,
                                            'positive_percentage': positive_percentage, })


def search_movies(request):
    if request.method == "POST":
        searched = request.POST['searched']
        searched_movies = Scrapper.get_search_movies(searched)
        pre_movie_list = DictionaryManager.get_all_information(searched_movies)
        all_information_movies = DictionaryManager.change_keys_in_dictionary_list(pre_movie_list)
        DictionaryManager.set_fix_imdb_url(all_information_movies)
        for movie_information in range(0, len(all_information_movies)):
            gender_list = all_information_movies[movie_information]['genre']
            check = Movie.objects.filter(name=all_information_movies[movie_information]['name'])
            if not check:
                Movie(name=all_information_movies[movie_information]['name'], raw=all_information_movies[movie_information]).save()
                obj: Movie = Movie.objects.get(name=all_information_movies[movie_information]['name'])
                for gender in gender_list:
                    correct_gender = gender.replace(" ", "")
                    obj.gender.add(GenderMovies.objects.get_or_create(gender=correct_gender)[0])

        db_movies = Movie.objects.filter(name__regex=rf'({searched})+')
        return render(request, 'searched_movies.html', {'movies': db_movies})
    else:
        return render(request, 'searched_movies.html',
                      {})


def get_home_page(request):
    list_of_top_movies_check = Movie.objects.filter(is_top_250=True)
    if list_of_top_movies_check:
        return render(request, 'index.html', {'movies': list_of_top_movies_check})
    else:
        movies_source = json.loads(views.request_top_movies(request).content)
        for movie in movies_source:
            gender_list = movie['genre']
            check = Movie.objects.filter(name=movie['name'])
            if not check:
                Movie(name=movie['name'], raw=movie, is_top_250=True).save()
                obj: Movie = Movie.objects.get(name=movie['name'])
                for i in gender_list:
                    correct_gender = i.replace(" ", "")
                    obj.gender.add(GenderMovies.objects.get_or_create(gender=correct_gender)[0])
        movies = Movie.objects.all()
    return render(request, 'index.html', {'movies': movies})


def like(request):
    if request.method == 'POST':
        result = ''
        id: int = request.POST.get('postid')
        p_id: int = id
        user_id: int = request.user.id
        comments = CommentsLikes.objects.filter(user_id=user_id, comment_id=p_id)
        if not comments:
            CommentsLikes(
                like=True,
                comment_id=p_id,
                user_id=user_id).save()
            post = get_object_or_404(Comments, id=p_id)
            post.likes += 1
            post.save()
            result = post.likes
            return JsonResponse({'result': result, 'p_id': p_id, })
        else:
            comment_like = get_object_or_404(CommentsLikes, comment_id=p_id)
            if not comment_like.like:
                comment_like.like = True
                comment_like.save()
                post = get_object_or_404(Comments, id=p_id)
                post.likes += 1
                post.save()
                result = post.likes
                return JsonResponse({'result': result, 'p_id': p_id, })
            if comment_like.like:
                post = get_object_or_404(Comments, id=id)
                result = post.likes
                return JsonResponse({'result': result, 'p_id': p_id, })

    return JsonResponse({'result': result, 'p_id': p_id, })


def dislike(request):
    if request.method == 'POST':
        result = ''
        p_id: int = request.POST.get('postid')
        user_id: int = request.user.id
        comments = CommentsLikes.objects.filter(user_id=user_id, comment_id=p_id)
        if not comments:
            CommentsLikes(
                like=False,
                comment_id=p_id,
                user_id=request.user.id).save()

src/backend/home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>AI For You</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <link
      rel="stylesheet"
      href="{% static '../static/assets/css/main.css' %}"
    />
    {% block extrastyle %}{% endblock extrastyle %}
    <noscript>
      <link
        rel="stylesheet"
        href="{% static '../static/assets/css/noscript.css'%}"
      />
    </noscript>
  </head>
  <body class="is-preload">
    {% block header %} {% include './header.html' %} {% endblock %}
    <div class="dynamicContent">{% block content %}{% endblock content %}</div>
    {% block footer %} {% include './footer.html' %} {% endblock %}

    <script src="{% static '../static/assets/js/jquery.min.js'%}"></script>
    <script src="{% static '../static/assets/js/jquery.scrollex.min.js'%}"></script>
    <script src="{% static '../static/assets/js/jquery.scrolly.min.js'%}"></script>
    <script src="{% static '../static/assets/js/browser.min.js'%}"></script>
    <script src="{% static '../static/assets/js/breakpoints.min.js'%}"></script>
    <script src="{% static '../static/assets/js/util.js'%}"></script>
    <script src="{% static '../static/assets/js/main.js'%}"></script>
    <script src="{% static '../static/assets/js/animation.js'%}"></script>
  </body>
</html>

src/backend/home/templates/detail.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Tutorial</title>
    <!-- Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500"
      rel="stylesheet"
    />
    <!-- CSS -->
    <link rel="stylesheet" href="{% static '../static/assets/css/style.css'%}" />
    <meta name="robots" content="noindex,follow" />
  </head>

  <body>
    <main class="container">
      <!-- Left Column / Headphones Image -->
      <div class="left-column">
         <img src="{% static '../static/images/cover.jpg' %}"/>
      </div>

      <!-- Right Column -->
      <div class="right-column">
        <!-- Product Description -->
        <div class="product-description">
          <span>Movie Details</span>
          <h1>Movie Title</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>

        <!-- Product Configuration -->
        <div class="product-configuration">
          <!-- Product Color -->
          <div class="product-color">
            <span>Actions</span>

            <div class="color-choose">
              <div>
                <input
                  data-image="red"
                  type="radio"
                  id="red"
                  name="color"
                  value="red"
                  checked
                />
                <label for="red"><span></span></label>
              </div>
              <div>
                <input
                  data-image="blue"
                  type="radio"
                  id="blue"
                  name="color"
                  value="blue"
                />
                <label for="blue"><span></span></label>
              </div>
              <div>
                <input
                  data-image="black"
                  type="radio"
                  id="black"
                  name="color"
                  value="black"
                />
                <label for="black"><span></span></label>
              </div>
            </div>
          </div>

        <!-- Product Pricing -->
        <div class="product-price">
          <span>Needs Premium User!</span>
          <a href="#" class="cart-btn">Get Premium</a>
        </div>
      </div>
    </main>

    <!-- Scripts -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"
      charset="utf-8"
    ></script>
    <script src="{% static '../static/assets/js/script.js'%}" charset="utf-8"></script>
  </body>
</html>

src/backend/home/templates/footer.html
<!DOCTYPE html>
<html>
   <body>
      <footer id="footer">
         <section>
            <h3>Social</h3>
            <ul class="icons alt">
               <li><a style="font-size: 15px !important;" href="https://github.com/mjcencarnacao/diam-project" target="_blank" class="icon brands alt fa-github">
                  &nbsp;All Rights Reserved To Grupo 11<span class="label">GitHub</span></a></li>
            </ul>
         </section>
         </section>
      </footer>
   </body>
</html>

src/backend/home/templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
  <body>
    <div id="intro">
      <h1>AI<br />For You</h1>
      <p>
        AI Powered Open Source Tool that helps you find the right movie<br />IMDB
        TOP 250 Database
      </p>
      <ul class="actions">
        <li>
          <a href="#header" class="button icon solid solo fa-arrow-down scrolly"
            >Continue</a
          >
        </li>
      </ul>
    </div>
    <header id="header">
      <a href="{% url 'home:home_page' %}" class="logo">AI For You</a>
    </header>
    <nav id="nav">
      <ul class="links">
        <li class="{% if 'top' in request.path %} active {% endif %}"><a href="{% url 'home:home_page' %}">IMDB Top 250 Movies</a></li>
        {% if user.is_authenticated %}
        <li class="{% if 'Profile' in request.path %} active {% endif %}"><a href="{% url 'members:logged_profile_user' %}">Profile</a></li>
        {% if myuser.is_premium_user or myuser.is_pro_user or user.is_premium_user or user.is_pro_user %}
        <li class="{% if 'watchlist' in request.path %} active {% endif %}"><a href="{% url 'members:watchlist' request.user.id %}">Watchlist</a></li>
        {% endif %}
        {% else %}
        <li class="{% if 'login' in request.path %} active {% endif %}"><a href="{% url 'members:login_user' %}">Login</a></li>
        <li class="{% if 'register' in request.path %} active {% endif %}"><a href="{% url 'members:register' %}">Register</a></li>
        {% endif %}
      </ul>
      {% if user.is_authenticated %}
      <form style="display: inline !important; margin-bottom: 0px !important;padding-left: 45% !important;" class="d-flex" method=POST action="{% url 'home:movie-search' %}">
        {% csrf_token %}
        <input style="display: inline !important; width: 80% !important; height: 45% !important; font-size: medium !important;"
        class="form-control" type="text" placeholder="Search Movie" aria-label="Search" name="searched">&nbsp;
        <button id="-search-btn-" onmouseout="searchbuttonout('-search-btn-')" onmouseover="searchbuttonover('-search-btn-')" class="fas fa-search"
        style="color: #ffffff !important; line-height: 0 !important; height: inherit !important;display: inline !important; padding-left: 0 !important; padding-right: 0 !important; border: 0px !important; outline: 0px !important;" type="submit">
        </button>
      </input>
      </form>
      {% endif %}
      <ul class="icons">
        {% if user.is_authenticated %}
        <li style="padding-right: 0 !important;">
          {% else %}
        <li>
          {% endif %}
          <a href="https://github.com/mjcencarnacao/diam-project" target="_blank" class="icon brands fa-github"
            ><span class="label">GitHub</span></a
          >
        </li>
        {% if user.is_authenticated %}
        <li>
          {% if request.user.profile_pic %}
          <a style="border-bottom: dotted 0px !important" href="{% url 'members:logged_profile_user' %}">
          <img
            src="{{ request.user.profile_pic.url }}"
            style="max-width: 40px; max-height: 28px; border-radius: 50%; vertical-align: -5%;"
          />
          </a>
          {% else %}
          <a style="border-bottom: dotted 0px !important" href="{% url 'members:logged_profile_user' %}">
            <img src="{% static 'default-user-image.png' %}"
                  style="max-width: 28px; max-height: 28px; border-radius: 50%; vertical-align: -5%;"
                  />
          </a>
          {% endif %}
        </li>
        <li>
          <a style="border-bottom: dotted 0px !important" href="{% url 'members:logout' %}" class="fas fa-sign-out-alt"></a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </body>
</html>

src/backend/home/templates/index.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html>
  <body class="is-preload">
    {% block content %}

    <div id="main">
      <article class="post featured">
        <header class="major">
          <span class="date">Updated IMDB List</span>
          <h2>
            <a
              >Not Sure about<br />
              what to watch?
            </a
            >
          </h2>
          <p>
            Here are the Top 250 movies of all time, powered by AI and Django<br />
            Comments in movies are analysed by our AI solution in order to give
            you a general view of what the public thinks of.
          </p>
        </header>
        <ul class="actions special">
          <li>
            <a href="https://www.imdb.com/chart/top/" target="_blank" class="button large">Visit IMDB Official Website</a>
          </li>
        </ul>
      </article>
      <!-- Posts -->
      <section class="posts">
        {% for movie in movies %}
        <article>
          <header>
            <span class="date">{{ movie.raw | get_movie_year }}</span>
            <h2>
              <a href="{% url 'home:movie-details' movie.id %}"
                >{{ movie.raw | get_movie_name }}</a
              >
            </h2>
          </header>
          <a href="{% url 'home:movie-details' movie.id %}" class="image fit"
            ><img src="{{ movie.raw | get_movie_cover }}" alt=""
          /></a>
          <p>{{ movie.raw | get_movie_description }}</p>
          <ul class="actions special">
            <li>
              <a href="{% url 'home:movie-details' movie.id %}" class="button"
                >
                {{ movie | get_movie_likes }} likes</a
              >
            </li>
          </ul>
        </article>
        {% endfor %}
      </section>
    </div>
    {% endblock content %}
  </body>
</html>

src/backend/home/templates/searched_movies.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 {% block content %}
 <div id="main">
      <article class="post featured">
        <header class="major">
          <span class="date">Updated IMDB List</span>
          <h2>
            <a href="#"
              >Not Sure about<br />
              what to watch?</a
            >
          </h2>
          <p>
            Here are the Top 250 movies of all time, powered by AI and Django<br />
            Comments in movies are analysed by our AI solution in order to give
            you a general view of what the public thinks of.
          </p>
        </header>
        <ul class="actions special">
          <li>
            <a href="#" class="button large">Visit IMDB Official Website</a>
          </li>
        </ul>
      </article>
   <section class="posts">
        {% for movie in movies %}
        <article>
          <header>
            <span class="date">{{ movie.raw | get_movie_year }}</span>
            <h2>
              <a href="{% url 'home:movie-details' movie.id %}"
                >{{ movie.raw | get_movie_name }}</a
              >
            </h2>
          </header>
          <a href="{% url 'home:movie-details' movie.id %}" class="image fit"
            ><img src="{{ movie.raw | get_movie_cover }}" alt=""
          /></a>
          <p>{{ movie.raw | get_movie_description }}</p>
          <ul class="actions special">
            <li>
              <a href="{% url 'home:movie-details' movie.id %}" class="button"
                >AI Rating</a
              >
            </li>
          </ul>
        </article>
        {% endfor %}
      </section>

</body>
    {% endblock content %}
</html>